<?php

/**
 * @file
 * Yeah
 */
 
 
 /**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function form_submit_help($path, $arg)
{
	switch ($path)
	{
    	case "admin/help#form_submit":
      		return '<p>' . t("Handles the webform submitions.") . '</p>';
      		break;
	}
}
